"""Synchronize this personal harness. Default: read-only check. Python 3.10+."""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
import hashlib
import json
from pathlib import Path
import re


def digest(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def within(root: Path, relative: str) -> Path:
    path = (root / relative).resolve()
    if not path.is_relative_to(root.resolve()) or path == root.resolve():
        raise ValueError(f"Path escapes its root: {relative}")
    return path


def desired_files(home: Path) -> dict[str, bytes]:
    harness = within(home, ".agents/harness")
    manifest = json.loads((harness / "manifest.json").read_text(encoding="utf-8"))
    core = (harness / "CORE.md").read_text(encoding="utf-8").strip() + "\n"
    header = "<!-- Generated by Eddie's harness; edit ~/.agents/harness/CORE.md and run scripts/sync.py --apply. -->\n\n"
    result = {
        ".codex/AGENTS.md": (header + core).encode(),
        ".claude/CLAUDE.md": (header + core).encode(),
        ".cursor/rules/00-work-standard.mdc": (
            "---\ndescription: Eddie's personal working standard\nalwaysApply: true\n---\n\n"
            + header + core
        ).encode(),
    }
    for skill in manifest["skills"]:
        name = skill["name"]
        if not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", name):
            raise ValueError(f"Invalid skill name: {name}")
        source = within(home, f".agents/skills/{name}")
        if "SKILL.md" not in skill["files"]:
            raise ValueError(f"Missing SKILL.md in manifest: {name}")
        # Copy only the explicit inventory. Never sweep in plugins, hooks, or caches.
        for relative in skill["files"]:
            file = within(source, relative)
            if not file.is_file():
                raise ValueError(f"Missing skill resource: {file}")
            destination = f".claude/skills/{name}/{relative}"
            within(home, destination)
            if destination in result:
                raise ValueError(f"Duplicate destination: {destination}")
            result[destination] = file.read_bytes()
    return result


def synchronize(home: Path, apply: bool = False) -> dict:
    home = home.resolve()
    harness = within(home, ".agents/harness")
    desired = desired_files(home)
    state_path = harness / "state.json"
    state = json.loads(state_path.read_text(encoding="utf-8")) if state_path.exists() else {"files": {}}
    previous = state["files"]
    changes = []
    conflicts = []
    for relative in sorted(set(previous) - set(desired)):
        conflicts.append(f"Previously managed file removed from inventory; reconcile manually: {relative}")
    for relative, data in desired.items():
        target = within(home, relative)
        if target.exists() and not target.is_file():
            conflicts.append(f"Destination is not a file: {relative}")
            continue
        original = target.read_bytes() if target.exists() else None
        if original == data:
            continue
        changes.append((relative, data, original))
        if original is not None and original.strip():
            if relative not in previous or digest(original) != previous[relative]:
                conflicts.append(f"Independent destination edits; merge into canonical source first: {relative}")
    report = {"mode": "apply" if apply else "check", "managed_files": len(desired),
              "changes": [c[0] for c in changes], "conflicts": conflicts,
              "ok": not changes and not conflicts}
    # Complete the preflight before writing anything.
    if not apply or conflicts:
        return report
    if changes:
        stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%S%fZ")
        backup = within(harness, f"backups/{stamp}")
        backup.mkdir(parents=True, exist_ok=False)
        receipt = []
        for relative, data, original in changes:
            entry = {"path": relative, "existed": original is not None,
                     "before_sha256": digest(original) if original is not None else None,
                     "after_sha256": digest(data)}
            if original is not None:
                saved = within(backup, relative)
                saved.parent.mkdir(parents=True, exist_ok=True)
                saved.write_bytes(original)
            receipt.append(entry)
        # Receipt and backups exist even if a later write is interrupted.
        (backup / "receipt.json").write_text(json.dumps(receipt, indent=2) + "\n", encoding="utf-8")
        for relative, data, _ in changes:
            target = within(home, relative)
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(data)
        report["backup"] = str(backup)
    new_state = {"schema_version": 1, "files": {p: digest(b) for p, b in desired.items()}}
    if state != new_state:
        pending = harness / "state.json.tmp"
        pending.write_text(json.dumps(new_state, indent=2) + "\n", encoding="utf-8")
        pending.replace(state_path)
    report["ok"] = True
    return report


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--apply", action="store_true", help="Write reviewed canonical sources to application locations")
    parser.add_argument("--home", type=Path, default=Path.home(), help="Alternate home for isolated tests or another installation")
    args = parser.parse_args()
    try:
        result = synchronize(args.home, args.apply)
    except (OSError, ValueError, KeyError, TypeError) as error:
        print(json.dumps({"ok": False, "error": str(error)}, indent=2))
        return 2
    print(json.dumps(result, indent=2))
    return 0 if result["ok"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
